{% set name = "faampy" %}
{% set version = "0.1.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: faampy-{{ version }}.tar.gz
    url: https://github.com/ncasuk/faampy/archive/{{ version }}.tar.gz
    sha256: 7cddf84430b54920af7b984e2f206bad848f81de39e74c51e65b346780a95ead

build:
    skip: True  # [py>35]
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - asteval
        - basemap
        - cartopy
        - ephem
        - matplotlib >=1.2.0
        - setuptools
        - netcdf4 >=1.0
        - numpy
        - scipy
        - pyhdf
        - psutil
        - pandas
        - gdal
        - exifread
        - fiona
        - gdal
        - georaster
        - haversine
        - pillow
        - libspatialite
        - seaborn
        - simplekml
        - sqlite
        - xarray

test:
    imports:
        - faampy

about:
    home: http://www.faam.ac.uk
    license: LGPLv3
    summary: 'FAAM aircraft data processing module'

extra:
    recipe-maintainers:
        - awellpott
