{% set name = "faampy" %}
{% set version = "v0.1.3" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: faampy-{{ version }}.tar.gz
    url: https://github.com/ncasuk/faampy/archive/{{ version }}.tar.gz
    sha256: 38590ea676b86222b1fec83bb8291912a84ea2bcedab928761fc89bbafe03a5f

build:
    skip: True  # [py>35]
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - basemap
        - cartopy
        - ConfigParser
        - ephem
        - matplotlib >=1.4.0
        - setuptools
        - netcdf4 >=1.0
        - numpy
        - scipy
        - pandas
        - gdal
        - exifread
        - fiona
        - gdal
        - georaster
        - haversine
        - pillow
        - libspatialite
        - seaborn
        - simplekml
        - sqlite
        - xarray

test:
    imports:
        - faampy

about:
    home: http://www.faam.ac.uk
    license: LGPLv3
    summary: 'FAAM aircraft data processing module'

extra:
    recipe-maintainers:
        - awellpott
