{% set name = "faampy" %}
{% set version = "0.1.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/ncasuk/faampy.git
    git_tag: {{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - python >=2.7,<=3.5
        - setuptools

    run:
        - python
        - python >=2.7,<=3.5
        - asteval
        - basemap
        - cartopy
        - ConfigParser
        - ephem
        - matplotlib >=1.2.0
        - setuptools
        - netcdf4 >=1.0
        - numpy
        - scipy
        - pyhdf
        - psutil
        - pandas
        - gdal
        - exifread
        - fiona
        - gdal
        - georaster
        - haversine
        - pillow
        - libspatialite
        - seaborn
        - simplekml
        - sqlite
        - xarray

test:
    imports:
        - faampy

about:
    home: http://www.faam.ac.uk
    license: LGPLv3
    summary: 'FAAM aircraft data processing module'

extra:
    recipe-maintainers:
        - awellpott
